// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace GdkSample_SimpleHttp
{
public static class GdkPlatformSettings
{
    public static string gameConfigTitleId = "77c17f51";
    public static string gameConfigScid = "00000000-0000-0000-0000-000077c17f51";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
}
}
