// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace GdkSample_SimpleMPSD
{
    public static class GdkPlatformSettings
    {
        public static string gameConfigTitleId = "799A2E03";
        public static string gameConfigScid = "00000000-0000-0000-0000-0000799a2e03";
    }
}
