<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <StartupObject>QueryingTimingCapture.Program</StartupObject>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <AnalysisLevel>none</AnalysisLevel>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <CodeAnalysisRuleSet></CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="App.xaml" />
    <None Remove="MainWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="EntityFramework" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" />
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="SampleQueries\ShowCPUEvents.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SampleQueries\ShowGPUEvents.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SampleQueries\ShowPIXCounterNameList.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SampleQueries\ShowPIXCounterTitleCPUBusy.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="SampleQueries\" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="MainWindow.xaml" />
  </ItemGroup>
</Project>