//-----------------------------------------------------------------------------
// AccessToken.cs
//
// Xbox Advanced Technology Group (ATG)
// Copyright (C) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------

using Newtonsoft.Json;
using System;

namespace Microsoft.StoreServices
{
    /// <summary>
    /// Access tokens are generated by your service and either used as the Authorization 
    /// header for calls to the Microsoft.Store services, or sent to the client to
    /// generate a UserStoreId.  The specified Audience of the access token will
    /// determine what it is used for:
    /// Service Access Token -     https://onestore.microsoft.com - Used as the bearer token
    ///                            in the Authorization header of service-to-service calls. 
    /// Purchase Access Token -    https://onestore.microsoft.com/b2b/keys/create/purchase
    ///                            Sent to the client to generate a UserPurchaseId
    /// Collections Access Token - https://onestore.microsoft.com/b2b/keys/create/collections
    ///                            Sent to the client to generate a UserCollectionsId
    /// </summary>
    public class AccessToken
    {
        /// <summary>
        /// Lifetime of the token in seconds from when it was created
        /// </summary>
        [JsonProperty("expires_in")] public uint ExpiresIn { get; set; }

        /// <summary>
        /// Lifetime of the token in seconds from when it was created
        /// </summary>
        [JsonProperty("ext_expires_in")] public uint ExtExpiredIn { get; set; }

        /// <summary>
        /// Seconds from the Unix Epoc that represents the UTC datetime the token will expire
        /// </summary>
        [JsonProperty("expires_on")] public uint EpochExpiresOn { get; set; }

        /// <summary>
        /// Seconds from the Unix Epoc that represents the UTC datetime the token starts being valid and can be used.
        /// </summary>
        [JsonProperty("not_before")] public uint EpochValidAfter { get; set; }

        /// <summary>
        /// Audience URI tied to the token which determines its type and which Microsoft Store Service it can be used with.
        /// </summary>
        [JsonProperty("resource")] public string Audience { get; set; }
        
        /// <summary>
        /// Actual token to be used in calling the services or obtaining User Store Ids
        /// </summary>
        [JsonProperty("access_token")] public string Token { get; set; }

        /// <summary>
        /// The UTC date and time when the Access Token expires
        /// </summary>
        public DateTime ExpiresOn => DateTime.UnixEpoch.AddSeconds(EpochExpiresOn);

        /// <summary>
        /// The UTC date and time when the Access Token becomes valid and can be used
        /// </summary>
        public DateTime ValidAfter => DateTime.UnixEpoch.AddSeconds(EpochValidAfter);
    }

    /// <summary>
    /// Audience URI string values for each of the Access Token types used for Microsoft Store Services auth
    /// </summary>
    public class AccessTokenAudienceTypes
    {
        /// <summary>
        /// Service access tokens identify the AAD tenant and your service.
        /// This token is used in the Authorization header of all calls to the Microsoft Store Services.
        /// </summary>
        public const string Service     = "https://onestore.microsoft.com";

        /// <summary>
        /// Collections access tokens are passed to the client and used to generate UserCollectionsIds.
        /// </summary>
        public const string Collections = "https://onestore.microsoft.com/b2b/keys/create/collections";

        /// <summary>
        /// Purchase access tokens are passed to your client app and used to generate UserPurchaseIds.  
        /// </summary>
        public const string Purchase    = "https://onestore.microsoft.com/b2b/keys/create/purchase";
    }
}
