<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <Import Condition="Exists($(ATGBuildProps))" Project="$(ATGBuildProps)" />
  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\DevKitAgentApi.yaml" CodeGenerator="NSwagCSharp" Namespace="Xbox.AgentProtocol" Link="OpenAPIs\DevKitAgentApi.yaml">
      <Options>/GenerateClientClasses:false /GenerateExceptionClasses:false</Options>
    </OpenApiReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="7.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="13.20.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OpenAPIs\" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="OpenAPIs\CopyAgentYamlIfNewer.bat &quot;$(GameDK)\toolKit\include\DevKitAgentAPI.yaml&quot; &quot;OpenAPIs\DevKitAgentAPI.yaml&quot; obj" />
  </Target>

</Project>
