// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace GdkSample_SocialManager
{
public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "75CC8DA7";
    public static string gameConfigScid = "00000000-0000-0000-0000-000075cc8da7";
#elif UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "75CC8DA7";
    public static string gameConfigScid = "00000000-0000-0000-0000-000075cc8da7";
#else
    public static string gameConfigTitleId = "75CC8DA7";
    public static string gameConfigScid = "00000000-0000-0000-0000-000075cc8da7";
#endif
}
}
