// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "7A8F76D7";
    public static string gameConfigScid = "00000000-0000-0000-0000-00007a8f76d7";
    public static string gameConfigSandbox = "";
#elif UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "7A8F76D7";
    public static string gameConfigScid = "00000000-0000-0000-0000-00007a8f76d7";
    public static string gameConfigSandbox = "";
#else
    public static string gameConfigTitleId = "7A8F76D7";
    public static string gameConfigScid = "00000000-0000-0000-0000-00007a8f76d7";
    public static string gameConfigSandbox = "";
#endif
}
