// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

public static class GdkPlatformSettings
{
    public static string gameConfigTitleId = "664cd024";
    public static string gameConfigScid = "00000000-0000-0000-0000-0000664cd024";
    public static string gameConfigSandbox = "";
}
