//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteIterationToolsSample {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteIterationToolsSample.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///Wait for the active operation to return before closing. If it appears stalled, choose Cancel for copy or Stop waiting for delete when available, then wait for the call to return. If it remains unresponsive, end RemoteIterationToolsSample.exe in Task Manager as a last resort. Force-closing does not undo completed transfers or deletions, or confirm that the remote operation stopped.
        ///.
        /// </summary>
        public static string ActiveOperationClosingGuidance {
            get {
                return ResourceManager.GetString("ActiveOperationClosingGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Deployment.
        /// </summary>
        public static string AppWindowTitle {
            get {
                return ResourceManager.GetString("AppWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string ArchiveAttributeText {
            get {
                return ResourceManager.GetString("ArchiveAttributeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match any selected attribute. No selection means no attribute filtering; exclusions win..
        /// </summary>
        public static string AttributeFilterGuidance {
            get {
                return ResourceManager.GetString("AttributeFilterGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///✗ Callback processing failed: {0} (HRESULT 0x{1:X8}). A callback failure does not stop native copy or replace its final HRESULT.
        ///.
        /// </summary>
        public static string CallbackFailureFormat {
            get {
                return ResourceManager.GetString("CallbackFailureFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command output.
        /// </summary>
        public static string CommandOutputAutomationName {
            get {
                return ResourceManager.GetString("CommandOutputAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read the final result here and in the status above. Progress alone does not confirm completion..
        /// </summary>
        public static string CommandOutputGuidance {
            get {
                return ResourceManager.GetString("CommandOutputGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command Output.
        /// </summary>
        public static string CommandOutputHeading {
            get {
                return ResourceManager.GetString("CommandOutputHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///Cancellation requested; waiting for the copy result.
        ///.
        /// </summary>
        public static string CopyCancellationRequestedOutput {
            get {
                return ResourceManager.GetString("CopyCancellationRequestedOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation requested; waiting for copy to return..
        /// </summary>
        public static string CopyCancellationRequestedStatus {
            get {
                return ResourceManager.GetString("CopyCancellationRequestedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✗ Cancellation signal failed: {0} (HRESULT 0x{1:X8}). Copy may continue.
        ///.
        /// </summary>
        public static string CopyCancellationSignalExceptionFormat {
            get {
                return ResourceManager.GetString("CopyCancellationSignalExceptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✗ Cancellation signal failed; copy may continue. Cancellation intent is retained.
        ///.
        /// </summary>
        public static string CopyCancellationSignalFailedOutput {
            get {
                return ResourceManager.GetString("CopyCancellationSignalFailedOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation signal failed; waiting for copy to return..
        /// </summary>
        public static string CopyCancellationSignalFailedStatus {
            get {
                return ResourceManager.GetString("CopyCancellationSignalFailedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation signal returned HRESULT 0x{0:X8}.
        ///.
        /// </summary>
        public static string CopyCancellationSignalReturnedFormat {
            get {
                return ResourceManager.GetString("CopyCancellationSignalReturnedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy exclude directory attributes.
        /// </summary>
        public static string CopyExcludeDirectoryAttributesAutomationName {
            get {
                return ResourceManager.GetString("CopyExcludeDirectoryAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude directory pattern.
        /// </summary>
        public static string CopyExcludeDirectoryPatternAutomationName {
            get {
                return ResourceManager.GetString("CopyExcludeDirectoryPatternAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excludes directories by name, not path. Wildcards * and ? are supported. Default excludes no directories. Exclusions take precedence over inclusions..
        /// </summary>
        public static string CopyExcludeDirectoryPatternToolTip {
            get {
                return ResourceManager.GetString("CopyExcludeDirectoryPatternToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy exclude file attributes.
        /// </summary>
        public static string CopyExcludeFileAttributesAutomationName {
            get {
                return ResourceManager.GetString("CopyExcludeFileAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude file pattern.
        /// </summary>
        public static string CopyExcludeFilePatternAutomationName {
            get {
                return ResourceManager.GetString("CopyExcludeFilePatternAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excludes files that match the specified names. Wildcards * and ? and semicolon-separated patterns are supported. Default excludes nothing. Exclusions take precedence over inclusions..
        /// </summary>
        public static string CopyExcludeFilePatternToolTip {
            get {
                return ResourceManager.GetString("CopyExcludeFilePatternToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation was also requested; this does not establish the failure&apos;s cause.
        ///.
        /// </summary>
        public static string CopyFailureCancellationNote {
            get {
                return ResourceManager.GetString("CopyFailureCancellationNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy include directory attributes.
        /// </summary>
        public static string CopyIncludeDirectoryAttributesAutomationName {
            get {
                return ResourceManager.GetString("CopyIncludeDirectoryAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy include file attributes.
        /// </summary>
        public static string CopyIncludeFileAttributesAutomationName {
            get {
                return ResourceManager.GetString("CopyIncludeFileAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include file pattern.
        /// </summary>
        public static string CopyIncludeFilePatternAutomationName {
            get {
                return ResourceManager.GetString("CopyIncludeFilePatternAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Includes files that match the specified names. Wildcards * and ? and semicolon-separated patterns are supported. Default includes everything. Exclusions take precedence over inclusions..
        /// </summary>
        public static string CopyIncludeFilePatternToolTip {
            get {
                return ResourceManager.GetString("CopyIncludeFilePatternToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to displaying remaining copy output..
        /// </summary>
        public static string CopyProgressDisplayingRemainingOutput {
            get {
                return ResourceManager.GetString("CopyProgressDisplayingRemainingOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied {0:N0} / {1:N0} bytes ({2:N0} / {3:N0} files); {4}.
        /// </summary>
        public static string CopyProgressStatusFormat {
            get {
                return ResourceManager.GetString("CopyProgressStatusFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to waiting for copy result..
        /// </summary>
        public static string CopyProgressWaitingForResult {
            get {
                return ResourceManager.GetString("CopyProgressWaitingForResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string DefaultCommonRootDisplayName {
            get {
                return ResourceManager.GetString("DefaultCommonRootDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete remote content.
        /// </summary>
        public static string DeleteButtonAutomationName {
            get {
                return ResourceManager.GetString("DeleteButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete....
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review the request before deleting..
        /// </summary>
        public static string DeleteButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Common Root alias.
        /// </summary>
        public static string DeleteCommonRootAutomationName {
            get {
                return ResourceManager.GetString("DeleteCommonRootAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common Root alias (optional).
        /// </summary>
        public static string DeleteCommonRootLabel {
            get {
                return ResourceManager.GetString("DeleteCommonRootLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blank uses the default Common Root. Ignored for absolute paths..
        /// </summary>
        public static string DeleteCommonRootToolTip {
            get {
                return ResourceManager.GetString("DeleteCommonRootToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote delete device.
        /// </summary>
        public static string DeleteDeviceAutomationName {
            get {
                return ResourceManager.GetString("DeleteDeviceAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete exclude directory attributes.
        /// </summary>
        public static string DeleteExcludeDirectoryAttributesAutomationName {
            get {
                return ResourceManager.GetString("DeleteExcludeDirectoryAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete exclude directory pattern.
        /// </summary>
        public static string DeleteExcludeDirectoryAutomationName {
            get {
                return ResourceManager.GetString("DeleteExcludeDirectoryAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude directory names.
        /// </summary>
        public static string DeleteExcludeDirectoryLabel {
            get {
                return ResourceManager.GetString("DeleteExcludeDirectoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory names, not paths. Supports * and ? wildcards. Blank excludes none..
        /// </summary>
        public static string DeleteExcludeDirectoryToolTip {
            get {
                return ResourceManager.GetString("DeleteExcludeDirectoryToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete exclude file attributes.
        /// </summary>
        public static string DeleteExcludeFileAttributesAutomationName {
            get {
                return ResourceManager.GetString("DeleteExcludeFileAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete exclude file pattern.
        /// </summary>
        public static string DeleteExcludeFilePatternAutomationName {
            get {
                return ResourceManager.GetString("DeleteExcludeFilePatternAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Names with * and ? wildcards; separate patterns with semicolons. Blank excludes none..
        /// </summary>
        public static string DeleteExcludeFilePatternToolTip {
            get {
                return ResourceManager.GetString("DeleteExcludeFilePatternToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ignored for single-file targets. Exclusions take precedence..
        /// </summary>
        public static string DeleteFiltersGuidance {
            get {
                return ResourceManager.GetString("DeleteFiltersGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete filters (folders only).
        /// </summary>
        public static string DeleteFiltersHeader {
            get {
                return ResourceManager.GetString("DeleteFiltersHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No delete request active..
        /// </summary>
        public static string DeleteIdleStatus {
            get {
                return ResourceManager.GetString("DeleteIdleStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete include directory attributes.
        /// </summary>
        public static string DeleteIncludeDirectoryAttributesAutomationName {
            get {
                return ResourceManager.GetString("DeleteIncludeDirectoryAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete include file attributes.
        /// </summary>
        public static string DeleteIncludeFileAttributesAutomationName {
            get {
                return ResourceManager.GetString("DeleteIncludeFileAttributesAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete include file pattern.
        /// </summary>
        public static string DeleteIncludeFilePatternAutomationName {
            get {
                return ResourceManager.GetString("DeleteIncludeFilePatternAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Names with * and ? wildcards; separate patterns with semicolons. Blank includes all..
        /// </summary>
        public static string DeleteIncludeFilePatternToolTip {
            get {
                return ResourceManager.GetString("DeleteIncludeFilePatternToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete files or folder contents on the selected device..
        /// </summary>
        public static string DeleteOverview {
            get {
                return ResourceManager.GetString("DeleteOverview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote path to delete.
        /// </summary>
        public static string DeletePathAutomationName {
            get {
                return ResourceManager.GetString("DeletePathAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote folder or single-file path to delete.
        /// </summary>
        public static string DeletePathLabel {
            get {
                return ResourceManager.GetString("DeletePathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relative to a Common Root, or an absolute path on the device..
        /// </summary>
        public static string DeletePathToolTip {
            get {
                return ResourceManager.GetString("DeletePathToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete request activity.
        /// </summary>
        public static string DeleteProgressAutomationName {
            get {
                return ResourceManager.GetString("DeleteProgressAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove delete root folder.
        /// </summary>
        public static string DeleteRootFolderAutomationName {
            get {
                return ResourceManager.GetString("DeleteRootFolderAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove root folder if empty.
        /// </summary>
        public static string DeleteRootFolderLabel {
            get {
                return ResourceManager.GetString("DeleteRootFolderLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applies to folder targets only..
        /// </summary>
        public static string DeleteRootFolderToolTip {
            get {
                return ResourceManager.GetString("DeleteRootFolderToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote deletion (optional).
        /// </summary>
        public static string DeleteSectionHeading {
            get {
                return ResourceManager.GetString("DeleteSectionHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device (selected above).
        /// </summary>
        public static string DeleteSelectedDeviceLabel {
            get {
                return ResourceManager.GetString("DeleteSelectedDeviceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deploy copies the build, then validates its remote path. It does not install or register the game. Cancel requests cancellation; wait for the final result..
        /// </summary>
        public static string DeployActionGuidance {
            get {
                return ResourceManager.GetString("DeployActionGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string DeployAdvancedOptionsHeader {
            get {
                return ResourceManager.GetString("DeployAdvancedOptionsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse for source folder.
        /// </summary>
        public static string DeployBrowseButtonAutomationName {
            get {
                return ResourceManager.GetString("DeployBrowseButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deploy build.
        /// </summary>
        public static string DeployButtonAutomationName {
            get {
                return ResourceManager.GetString("DeployButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string DeployButtonText {
            get {
                return ResourceManager.GetString("DeployButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment status is not confirmed because callback processing failed. Remote path validation skipped.
        ///.
        /// </summary>
        public static string DeployCallbackFailureMessage {
            get {
                return ResourceManager.GetString("DeployCallbackFailureMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel deployment.
        /// </summary>
        public static string DeployCancelButtonAutomationName {
            get {
                return ResourceManager.GetString("DeployCancelButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request copy cancellation, then wait for the native result. This does not confirm a complete deployment..
        /// </summary>
        public static string DeployCancelButtonToolTip {
            get {
                return ResourceManager.GetString("DeployCancelButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation was requested. Copy returning success does not confirm a complete deployment. Remote path validation skipped.
        ///.
        /// </summary>
        public static string DeployCancellationUnconfirmedMessage {
            get {
                return ResourceManager.GetString("DeployCancellationUnconfirmedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✗ Copy failed: HRESULT 0x{0:X8}.
        ///.
        /// </summary>
        public static string DeployCopyFailedFormat {
            get {
                return ResourceManager.GetString("DeployCopyFailedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination folder path.
        /// </summary>
        public static string DeployDestinationAutomationName {
            get {
                return ResourceManager.GetString("DeployDestinationAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Example: MyGame under the device&apos;s default Common Root, or an absolute path on the device..
        /// </summary>
        public static string DeployDestinationGuidance {
            get {
                return ResourceManager.GetString("DeployDestinationGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination Folder (device).
        /// </summary>
        public static string DeployDestinationLabel {
            get {
                return ResourceManager.GetString("DeployDestinationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote destination relative to the device&apos;s default Common Root, or an absolute device path..
        /// </summary>
        public static string DeployDestinationToolTip {
            get {
                return ResourceManager.GetString("DeployDestinationToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional copy filters. Leave patterns blank and attributes unselected for an unfiltered first deployment..
        /// </summary>
        public static string DeployFiltersGuidance {
            get {
                return ResourceManager.GetString("DeployFiltersGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment progress.
        /// </summary>
        public static string DeployProgressAutomationName {
            get {
                return ResourceManager.GetString("DeployProgressAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deploy Progress.
        /// </summary>
        public static string DeployProgressLabel {
            get {
                return ResourceManager.GetString("DeployProgressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a device, a local source folder, and a remote destination folder..
        /// </summary>
        public static string DeployRequiredInputsMessage {
            get {
                return ResourceManager.GetString("DeployRequiredInputsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source folder path.
        /// </summary>
        public static string DeploySourceAutomationName {
            get {
                return ResourceManager.GetString("DeploySourceAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local folder containing your build, e.g. C:\Builds\MyGame..
        /// </summary>
        public static string DeploySourceGuidance {
            get {
                return ResourceManager.GetString("DeploySourceGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Folder (this PC).
        /// </summary>
        public static string DeploySourceLabel {
            get {
                return ResourceManager.GetString("DeploySourceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a path or use Browse to select a folder.
        /// </summary>
        public static string DeploySourceToolTip {
            get {
                return ResourceManager.GetString("DeploySourceToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt; Deploying to {0}:{1}
        ///Source: {2}
        ///
        ///.
        /// </summary>
        public static string DeployStartingFormat {
            get {
                return ResourceManager.GetString("DeployStartingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. Deploy a local build.
        /// </summary>
        public static string DeployStepHeading {
            get {
                return ResourceManager.GetString("DeployStepHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device name or IP address.
        /// </summary>
        public static string DeviceAutomationName {
            get {
                return ResourceManager.GetString("DeviceAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use a target with Remote Tools running, already paired with this PC. Example: 192.168.1.100 or MyDevPC..
        /// </summary>
        public static string DeviceGuidance {
            get {
                return ResourceManager.GetString("DeviceGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device (IP address or host name).
        /// </summary>
        public static string DeviceLabel {
            get {
                return ResourceManager.GetString("DeviceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. Choose a paired device.
        /// </summary>
        public static string DeviceStepHeading {
            get {
                return ResourceManager.GetString("DeviceStepHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IP address or resolvable host name of an already-paired device. This sample does not discover or pair devices..
        /// </summary>
        public static string DeviceToolTip {
            get {
                return ResourceManager.GetString("DeviceToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude directory attributes.
        /// </summary>
        public static string ExcludeDirectoryAttributesLabel {
            get {
                return ResourceManager.GetString("ExcludeDirectoryAttributesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude Directory Pattern.
        /// </summary>
        public static string ExcludeDirectoryPatternLabel {
            get {
                return ResourceManager.GetString("ExcludeDirectoryPatternLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude file attributes.
        /// </summary>
        public static string ExcludeFileAttributesLabel {
            get {
                return ResourceManager.GetString("ExcludeFileAttributesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclude File Pattern.
        /// </summary>
        public static string ExcludeFilePatternLabel {
            get {
                return ResourceManager.GetString("ExcludeFilePatternLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string ExecutableAutomationName {
            get {
                return ResourceManager.GetString("ExecutableAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Example: MyGame\MyGame.exe. Relative paths start at the device&apos;s default Common Root, not Destination Folder. Absolute device paths also work..
        /// </summary>
        public static string ExecutableGuidance {
            get {
                return ResourceManager.GetString("ExecutableGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable to launch (device).
        /// </summary>
        public static string ExecutableLabel {
            get {
                return ResourceManager.GetString("ExecutableLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote executable relative to the device&apos;s default Common Root, or an absolute device path. This is not relative to Destination Folder..
        /// </summary>
        public static string ExecutableToolTip {
            get {
                return ResourceManager.GetString("ExecutableToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deploy first, or use an existing build on the device. Choose Launch, or Launch Suspended then Resume. Terminate stops the last game launched through this API on that device..
        /// </summary>
        public static string GameActionsGuidance {
            get {
                return ResourceManager.GetString("GameActionsGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string HiddenAttributeText {
            get {
                return ResourceManager.GetString("HiddenAttributeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include directory attributes.
        /// </summary>
        public static string IncludeDirectoryAttributesLabel {
            get {
                return ResourceManager.GetString("IncludeDirectoryAttributesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include file attributes.
        /// </summary>
        public static string IncludeFileAttributesLabel {
            get {
                return ResourceManager.GetString("IncludeFileAttributesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include File Pattern.
        /// </summary>
        public static string IncludeFilePatternLabel {
            get {
                return ResourceManager.GetString("IncludeFilePatternLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch game.
        /// </summary>
        public static string LaunchButtonAutomationName {
            get {
                return ResourceManager.GetString("LaunchButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string LaunchButtonText {
            get {
                return ResourceManager.GetString("LaunchButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. Launch and control the remote game.
        /// </summary>
        public static string LaunchStepHeading {
            get {
                return ResourceManager.GetString("LaunchStepHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch succeeded (Process ID: {0}, Thread ID: {1}).
        ///.
        /// </summary>
        public static string LaunchSucceededFormat {
            get {
                return ResourceManager.GetString("LaunchSucceededFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch game suspended.
        /// </summary>
        public static string LaunchSuspendedButtonAutomationName {
            get {
                return ResourceManager.GetString("LaunchSuspendedButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch Suspended.
        /// </summary>
        public static string LaunchSuspendedButtonText {
            get {
                return ResourceManager.GetString("LaunchSuspendedButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Iteration Tools.
        /// </summary>
        public static string MainHeading {
            get {
                return ResourceManager.GetString("MainHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Cancellation was also requested..
        /// </summary>
        public static string OperationFailureCancellationNote {
            get {
                return ResourceManager.GetString("OperationFailureCancellationNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Remote deletion may continue..
        /// </summary>
        public static string OperationFailureDeleteMayContinueNote {
            get {
                return ResourceManager.GetString("OperationFailureDeleteMayContinueNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///✗ {0} failed: {1} (HRESULT 0x{2:X8}).{3}{4}
        ///.
        /// </summary>
        public static string OperationFailureFormat {
            get {
                return ResourceManager.GetString("OperationFailureFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string ReadOnlyAttributeText {
            get {
                return ResourceManager.GetString("ReadOnlyAttributeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote path validation skipped.
        ///.
        /// </summary>
        public static string RemotePathValidationSkippedMessage {
            get {
                return ResourceManager.GetString("RemotePathValidationSkippedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validating remote path with WdRegisterRemoteXboxGame (not platform game registration).
        ///.
        /// </summary>
        public static string RemotePathValidationStartingMessage {
            get {
                return ResourceManager.GetString("RemotePathValidationStartingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resume game.
        /// </summary>
        public static string ResumeButtonAutomationName {
            get {
                return ResourceManager.GetString("ResumeButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeButtonText {
            get {
                return ResourceManager.GetString("ResumeButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve copies files only; it does not launch the game or validate the remote path as a deployment..
        /// </summary>
        public static string RetrieveActionGuidance {
            get {
                return ResourceManager.GetString("RetrieveActionGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse for retrieve destination folder.
        /// </summary>
        public static string RetrieveBrowseButtonAutomationName {
            get {
                return ResourceManager.GetString("RetrieveBrowseButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve artifacts.
        /// </summary>
        public static string RetrieveButtonAutomationName {
            get {
                return ResourceManager.GetString("RetrieveButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        public static string RetrieveButtonText {
            get {
                return ResourceManager.GetString("RetrieveButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieval status is not confirmed because callback processing failed.
        ///.
        /// </summary>
        public static string RetrieveCallbackFailureMessage {
            get {
                return ResourceManager.GetString("RetrieveCallbackFailureMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CopyFrom returned success, but callback processing failed..
        /// </summary>
        public static string RetrieveCallbackFailureStatus {
            get {
                return ResourceManager.GetString("RetrieveCallbackFailureStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel artifact retrieval.
        /// </summary>
        public static string RetrieveCancelButtonAutomationName {
            get {
                return ResourceManager.GetString("RetrieveCancelButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request retrieval cancellation, then wait for the native result..
        /// </summary>
        public static string RetrieveCancelButtonToolTip {
            get {
                return ResourceManager.GetString("RetrieveCancelButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation was requested. CopyFrom returning success does not confirm complete retrieval.
        ///.
        /// </summary>
        public static string RetrieveCancellationUnconfirmedMessage {
            get {
                return ResourceManager.GetString("RetrieveCancellationUnconfirmedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation requested; retrieval completeness not confirmed..
        /// </summary>
        public static string RetrieveCancellationUnconfirmedStatus {
            get {
                return ResourceManager.GetString("RetrieveCancellationUnconfirmedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve common root alias.
        /// </summary>
        public static string RetrieveCommonRootAutomationName {
            get {
                return ResourceManager.GetString("RetrieveCommonRootAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leave blank to use the default Common Root. Absolute remote source paths ignore this alias..
        /// </summary>
        public static string RetrieveCommonRootGuidance {
            get {
                return ResourceManager.GetString("RetrieveCommonRootGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common Root Alias (optional).
        /// </summary>
        public static string RetrieveCommonRootLabel {
            get {
                return ResourceManager.GetString("RetrieveCommonRootLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common Root alias for a relative remote source. Leave blank to use the default Common Root..
        /// </summary>
        public static string RetrieveCommonRootToolTip {
            get {
                return ResourceManager.GetString("RetrieveCommonRootToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieval completed successfully.
        ///.
        /// </summary>
        public static string RetrieveCompletedMessage {
            get {
                return ResourceManager.GetString("RetrieveCompletedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieval completed..
        /// </summary>
        public static string RetrieveCompletedStatus {
            get {
                return ResourceManager.GetString("RetrieveCompletedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✗ Retrieve failed: HRESULT 0x{0:X8}.
        ///.
        /// </summary>
        public static string RetrieveCopyFailedFormat {
            get {
                return ResourceManager.GetString("RetrieveCopyFailedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve failed during copy..
        /// </summary>
        public static string RetrieveCopyFailedStatus {
            get {
                return ResourceManager.GetString("RetrieveCopyFailedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///CopyFrom returned HRESULT 0x{0:X8}.
        ///.
        /// </summary>
        public static string RetrieveCopyReturnedFormat {
            get {
                return ResourceManager.GetString("RetrieveCopyReturnedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve local destination folder.
        /// </summary>
        public static string RetrieveDestinationAutomationName {
            get {
                return ResourceManager.GetString("RetrieveDestinationAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose an existing local folder where the retrieved artifacts will be copied..
        /// </summary>
        public static string RetrieveDestinationGuidance {
            get {
                return ResourceManager.GetString("RetrieveDestinationGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination Folder (this PC).
        /// </summary>
        public static string RetrieveDestinationLabel {
            get {
                return ResourceManager.GetString("RetrieveDestinationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local destination folder does not exist: {0}.
        /// </summary>
        public static string RetrieveDestinationNotFoundFormat {
            get {
                return ResourceManager.GetString("RetrieveDestinationNotFoundFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Existing local destination folder on this PC..
        /// </summary>
        public static string RetrieveDestinationToolTip {
            get {
                return ResourceManager.GetString("RetrieveDestinationToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CopyFrom returned; displaying remaining output..
        /// </summary>
        public static string RetrieveDisplayingRemainingOutput {
            get {
                return ResourceManager.GetString("RetrieveDisplayingRemainingOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid retrieval inputs.
        /// </summary>
        public static string RetrieveInvalidInputsTitle {
            get {
                return ResourceManager.GetString("RetrieveInvalidInputsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve failed before CopyFrom returned..
        /// </summary>
        public static string RetrieveOperationFailed {
            get {
                return ResourceManager.GetString("RetrieveOperationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy artifacts from the paired device to an existing folder on this PC. Deploy filters do not select remote files for this operation..
        /// </summary>
        public static string RetrieveOverview {
            get {
                return ResourceManager.GetString("RetrieveOverview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieving files; see Command Output for per-file activity..
        /// </summary>
        public static string RetrieveProgressActive {
            get {
                return ResourceManager.GetString("RetrieveProgressActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artifact retrieval progress.
        /// </summary>
        public static string RetrieveProgressAutomationName {
            get {
                return ResourceManager.GetString("RetrieveProgressAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve Progress.
        /// </summary>
        public static string RetrieveProgressLabel {
            get {
                return ResourceManager.GetString("RetrieveProgressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a device, a remote source folder, and a local destination folder..
        /// </summary>
        public static string RetrieveRequiredInputsMessage {
            get {
                return ResourceManager.GetString("RetrieveRequiredInputsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve remote source folder.
        /// </summary>
        public static string RetrieveSourceAutomationName {
            get {
                return ResourceManager.GetString("RetrieveSourceAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use a path relative to a Common Root, or an absolute path on the device..
        /// </summary>
        public static string RetrieveSourceGuidance {
            get {
                return ResourceManager.GetString("RetrieveSourceGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Folder (device).
        /// </summary>
        public static string RetrieveSourceLabel {
            get {
                return ResourceManager.GetString("RetrieveSourceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote source relative to the selected or default Common Root, or an absolute path on the device..
        /// </summary>
        public static string RetrieveSourceToolTip {
            get {
                return ResourceManager.GetString("RetrieveSourceToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt; Retrieving from {0}:{1}
        ///Local destination: {2}
        ///Common Root: {3}
        ///
        ///.
        /// </summary>
        public static string RetrieveStartingFormat {
            get {
                return ResourceManager.GetString("RetrieveStartingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4. Retrieve artifacts.
        /// </summary>
        public static string RetrieveStepHeading {
            get {
                return ResourceManager.GetString("RetrieveStepHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop waiting for delete.
        /// </summary>
        public static string StopWaitingButtonAutomationName {
            get {
                return ResourceManager.GetString("StopWaitingButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop waiting.
        /// </summary>
        public static string StopWaitingButtonText {
            get {
                return ResourceManager.GetString("StopWaitingButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stops the client wait, not deletion already started on the endpoint..
        /// </summary>
        public static string StopWaitingButtonToolTip {
            get {
                return ResourceManager.GetString("StopWaitingButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemAttributeText {
            get {
                return ResourceManager.GetString("SystemAttributeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminate game.
        /// </summary>
        public static string TerminateButtonAutomationName {
            get {
                return ResourceManager.GetString("TerminateButtonAutomationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminate.
        /// </summary>
        public static string TerminateButtonText {
            get {
                return ResourceManager.GetString("TerminateButtonText", resourceCulture);
            }
        }
    }
}
